"""replaced full text search from users.username with pg_trgm and changed the fts for posts.title to posts.content

Revision ID: b58dccccc834
Revises: d9e738d9dc2a
Create Date: 2026-01-03 21:12:56.893286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b58dccccc834'
down_revision: Union[str, Sequence[str], None] = 'd9e738d9dc2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('likes_user_id_fkey'), 'likes', type_='foreignkey')
    op.create_foreign_key(None, 'likes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('posts', sa.Column('content_search', postgresql.TSVECTOR(), sa.Computed('to_tsvector(\'english\', "content")', persisted=True), nullable=True))
    op.drop_index(op.f('idx_title_search'), table_name='posts', postgresql_using='gin')
    op.create_index('idx_content_search', 'posts', ['content_search'], unique=False, postgresql_using='gin')
    op.drop_column('posts', 'title_search')
    op.drop_index(op.f('idx_fullname_search'), table_name='users', postgresql_using='gin')
    op.create_index('idx_username_trgm', 'users', ['username'], unique=False, postgresql_using='gin', postgresql_ops={'username': 'gin_trgm_ops'})
    op.drop_column('users', 'username_search')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username_search', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english'::regconfig, (username)::text)", persisted=True), autoincrement=False, nullable=True))
    op.drop_index('idx_username_trgm', table_name='users', postgresql_using='gin', postgresql_ops={'username': 'gin_trgm_ops'})
    op.create_index(op.f('idx_fullname_search'), 'users', ['username_search'], unique=False, postgresql_using='gin')
    op.add_column('posts', sa.Column('title_search', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english'::regconfig, (title)::text)", persisted=True), autoincrement=False, nullable=True))
    op.drop_index('idx_content_search', table_name='posts', postgresql_using='gin')
    op.create_index(op.f('idx_title_search'), 'posts', ['title_search'], unique=False, postgresql_using='gin')
    op.drop_column('posts', 'content_search')
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.create_foreign_key(op.f('likes_user_id_fkey'), 'likes', 'posts', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
